server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CristianOrizano/config-repo  # Reemplaza con tu repositorio
          default-label: main